// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjWUcjGntPNWQWUIoJlEVDMu8yo9C-EwY',
    appId: '1:13169165124:web:f2eab79cf53687e2ad8d11',
    messagingSenderId: '13169165124',
    projectId: 'alzheimer-app-f5580',
    authDomain: 'alzheimer-app-f5580.firebaseapp.com',
    storageBucket: 'alzheimer-app-f5580.firebasestorage.app',
    measurementId: 'G-730K3XCVWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGVwdMHTbeodSPgyAS9q9PVVKE-PFf_oI',
    appId: '1:13169165124:android:b529f32fe0e8f28fad8d11',
    messagingSenderId: '13169165124',
    projectId: 'alzheimer-app-f5580',
    storageBucket: 'alzheimer-app-f5580.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKGwLj1NMZKrZ7JvM0rtzQLnekCgfun78',
    appId: '1:13169165124:ios:ff824eb2d76564f6ad8d11',
    messagingSenderId: '13169165124',
    projectId: 'alzheimer-app-f5580',
    storageBucket: 'alzheimer-app-f5580.firebasestorage.app',
    iosBundleId: 'com.example.alzheimerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKGwLj1NMZKrZ7JvM0rtzQLnekCgfun78',
    appId: '1:13169165124:ios:ff824eb2d76564f6ad8d11',
    messagingSenderId: '13169165124',
    projectId: 'alzheimer-app-f5580',
    storageBucket: 'alzheimer-app-f5580.firebasestorage.app',
    iosBundleId: 'com.example.alzheimerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjWUcjGntPNWQWUIoJlEVDMu8yo9C-EwY',
    appId: '1:13169165124:web:9c4eeb1a894834e8ad8d11',
    messagingSenderId: '13169165124',
    projectId: 'alzheimer-app-f5580',
    authDomain: 'alzheimer-app-f5580.firebaseapp.com',
    storageBucket: 'alzheimer-app-f5580.firebasestorage.app',
    measurementId: 'G-9ZN8JV580G',
  );
}
